haircut/urls.py
from django.urls import path
from . import views 


app_name='haircut' 

urlpatterns=[
    path("", views.home_page, name='home_page'), 
] 

salon/urls.py
from django.contrib import admin 
from django.urls import path, include 

urlpatterns=[ path("",include('haircut.urls')), 
path('admin/', admin.site.urls), ] 

haircut/models.py
from django.db import models

# Create your models here.
class Appointment(models.Model):
     time = models.CharField(max_length=180, null=True, blank=True)
     customer_name = models.CharField(max_length=180, null=True, blank=True)
     barber_name = models.CharField(max_length=180, null=True, blank=True)

haircut/views.py
from django.shortcuts import render
from . models import Appointment


def home_page(request):
    if request.method == 'POST':
        time = request.POST.get('time')
        customer_name = request.POST.get("customer_name")
        barber_name = request.POST.get("barber_name")
        comment_obj = Appointment.objects.create(
            time=time,
            customer_name=customer_name,
            barber_name=barber_name
        )
        all_appointments = Appointment.objects.all()
        context = {'appointments': all_appointments}

        return render(request, 'haircut/home_page.html', context)
    if request.method == "GET":
        appointments = Appointment.objects.all()
        context = {'appointments': appointments}   
        return render(request, 'haircut/home_page.html', context)

haircut/templates/haircut/home_page.html
<!DOCTYPE html>
<html>
<head>
 <title>Welcome to The Amy's haircut</title>
</head>
<body>
 <!-- Site Header -->
 <h1>Hi,I am Amy.Welcome to Amy's haircut</h1>
  <p>Your convenience is our duty</p>

<!-- Blog Post -->
 <h2>Here are all our items!</h2>
 
  <!-- Item 1 -->
  <p>.: ...</p>
  <p><img src="http://cdn.arn.com.au/media/7607343/hair-salon-introduces-a-quiet-chair.jpeg"></p>

  <!-- Item 2 -->
  <p>.: ...</p>
  <img src="http://www.reviewtrackers.com/wp-content/uploads/Hair-Salon-Review-Monitoring.jpg">

  <!-- Item 3 -->
  <p>.: ...</p>
  <img src="https://media.timeout.com/images/103251392/image.jpg">

 <!-- Social -->
 <button>Like</button>

<!-- Leave A Comment -->
 <h2>Place your Order</h2>
 <form action="{% url 'haircut:home_page' %}" method="POST">
 {% csrf_token %}    
 <input type="time" name="time" placeholder="Please Type the time"><br>
 <textarea name="customer_name" placeholder="Please Type Your customer name"></textarea><br>
 <textarea name="barber_name" placeholder="Please Type Your barber name"></textarea><br>
 <input type="submit" value="Place Your Order">
 </form>


<!-- Display Previous Comments -->

{% for appointment in appointments %}
    <p>Customer Name: {{appointment.customer_name}}</p>
    <p>Time of Appointment: {{appointment.time}}</p>
    <p>Barber: {{appointment.barber_name}}</p><hr>
{% endfor %}


    <h1>Your Order:</h1>
    <p>time: {{time}}</p>
    <p>customer_name: {{customer_name}}</p>
    <p>barber_name: {{barber_name}}</p>
</body>
</html>